### ISSUE TITLE
panic: runtime error: index out of range on ubuntu 20.04

### ISSUE THREAD

**Issue by bmhm** [shyiko/jabba#642]
Hi,

I just upgraded to Ubuntu 20.04 (dev version).

This happens when starting a new login shell or terminal:

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/shyiko/jabba/semver.pre070Compat(0xc000012bad, 0x9, 0x8194a0, 0x1)
        /Users/shyiko/Development/github/jabba/src/github.com/shyiko/jabba/semver/range.go:25 +0x278
github.com/shyiko/jabba/semver.ParseRange(0xc000012ba0, 0x16, 0xc00000f7d0, 0xc000089a00, 0xc00000a740)
        /Users/shyiko/Development/github/jabba/src/github.com/shyiko/jabba/semver/range.go:64 +0xac
github.com/shyiko/jabba/command.LsBestMatchWithVersionSlice(0xc00000a720, 0x4, 0x4, 0xc000012ba0, 0x16, 0xc00001204b, 0x15, 0xc000014c50, 0xd)
        /Users/shyiko/Development/github/jabba/src/github.com/shyiko/jabba/command/ls.go:41 +0x3f
github.com/shyiko/jabba/command.LsBestMatch(0xc000012ba0, 0x16, 0xc000012ba0, 0x16, 0x5, 0x78c0a0)
        /Users/shyiko/Development/github/jabba/src/github.com/shyiko/jabba/command/ls.go:37 +0x6d
github.com/shyiko/jabba/command.Use(0x7ffd0e1ad586, 0x7, 0xc000115bf0, 0x714f71, 0xc00012e510, 0xc00005b390, 0xc000115c30)
        /Users/shyiko/Development/github/jabba/src/github.com/shyiko/jabba/command/use.go:16 +0x75
main.use(0x7ffd0e1ad586, 0x7, 0x0, 0x0)
        /Users/shyiko/Development/github/jabba/src/github.com/shyiko/jabba/jabba.go:382 +0x39
main.main.func9(0xc000131000, 0xc00005b3f0, 0x1, 0x1, 0x0, 0x0)
        /Users/shyiko/Development/github/jabba/src/github.com/shyiko/jabba/jabba.go:269 +0x45
github.com/shyiko/jabba/vendor/github.com/spf13/cobra.(*Command).execute(0xc000131000, 0xc00005b390, 0x1, 0x1, 0xc000131000, 0xc00005b390)
        /Users/shyiko/Development/github/jabba/src/github.com/shyiko/jabba/vendor/github.com/spf13/cobra/command.go:565 +0x3b7
github.com/shyiko/jabba/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000130000, 0x0, 0x0, 0xc00005b330)
        /Users/shyiko/Development/github/jabba/src/github.com/shyiko/jabba/vendor/github.com/spf13/cobra/command.go:656 +0x2cc
github.com/shyiko/jabba/vendor/github.com/spf13/cobra.(*Command).Execute(0xc000130000, 0x81978e, 0x3)
        /Users/shyiko/Development/github/jabba/src/github.com/shyiko/jabba/vendor/github.com/spf13/cobra/command.go:615 +0x2b
main.main()
        /Users/shyiko/Development/github/jabba/src/github.com/shyiko/jabba/jabba.go:341 +0xb59
```

Ubuntu:

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu Focal Fossa (development branch)"
```

But this works:

```
$ jabba --version
0.11.2

 $ jabba ls
adopt@1.11.0-2
adopt-openj9@1.14.0-0
adopt-openj9@1.11.0-6
adopt-openj9@1.8.0-242
```

**Comment by bmhm** [comment]
… oh I think I just found it out.

This line in `jabba.sh`:
```
if [ ! -z "$(jabba alias default)" ]; then
    jabba use default
fi
```

… I had a line break in the default value, because unix files always end with a new line. Well, after removing the new line, it worked as intended.

Before:

```
$ jabba alias default
adopt-openj9@1.11.0-6

```

After:

```
$ jabba alias default
adopt-openj9@1.11.0-6
```

**Comment by michaelcusick** [comment]
@willcohen @bmarwell could one of you please close this since the issue has been resolved?

**Comment by bmarwell** [comment]
I haven’t seen a PR which removes the line break, if any.

**Comment by michaelcusick** [comment]
I'll open one.
